feature/frontend-vuetify
albertominetti/micro-finance pull request #2
Opened 2021-02-09 12:36 UTC by denial3x

2021-02-10 21:23 UTC, albertominetti requested changes

2021-02-10 21:23 UTC, albertominetti commented on .gitignore
> +/mf-frontend/node/
Meglio usare un'espressione tipo:
```
**/node/
**/node_modules/
**/dist/
```

2021-02-10 21:23 UTC, albertominetti commented on .gitignore
> +!**/src/test/**/reference/
Perché queste cartelle `reference `?

2021-02-10 21:23 UTC, albertominetti commented on mf-frontend/src/api/ForexApi.ts
> +      return null;
Da gestire con un log o almeno un TODO

2021-02-10 21:23 UTC, albertominetti commented on mf-frontend/src/model/ForexRate.ts
> +  get target(): string {
Possiamo evitare tutta questa duplicazione?

2021-02-10 21:23 UTC, albertominetti commented on pom.xml
> +        <module>mf-frontend</module>
Possiamo chiamarlo semplicemente frontend

2021-02-10 23:47 UTC, denial3x commented
Domani ne parliamo se riusciamo dopo lo stand-up ne parliamo 👍🏻

Il mer 10 feb 2021, 22:24 Alberto Minetti <notifications@github.com> ha
scritto:

> *@albertominetti* requested changes on this pull request.
> ------------------------------
>
> In .gitignore
> <https://github.com/albertominetti/micro-finance/pull/2#discussion_r574082330>
> :
>
> > @@ -1,8 +1,11 @@
>
>  HELP.md
>
>  target/
>
> +/mf-frontend/node/
>
>
> Meglio usare un'espressione tipo:
>
> **/node/
>
> **/node_modules/
>
> **/dist/
>
>
> ------------------------------
>
> In .gitignore
> <https://github.com/albertominetti/micro-finance/pull/2#discussion_r574082762>
> :
>
> >  !.mvn/wrapper/maven-wrapper.jar
>
> -!**/src/main/**/target/
>
> -!**/src/test/**/target/
>
> +!**/src/main/**/reference/
>
> +!**/src/test/**/reference/
>
>
> Perché queste cartelle reference ?
> ------------------------------
>
> In mf-frontend/src/api/ForexApi.ts
> <https://github.com/albertominetti/micro-finance/pull/2#discussion_r574086100>
> :
>
> > @@ -0,0 +1,18 @@
>
> +import ForexRate from "@/model/ForexRate";
>
> +import axios from "axios";
>
> +
>
> +export default class ForexApi {
>
> +  public static async getForexRate(
>
> +    target: string,
>
> +    reference: string
>
> +  ): Promise<ForexRate | null> {
>
> +    try {
>
> +      const { data } = await axios.get(
>
> +        `/forex-service/rates/${target}/${reference}`
>
> +      );
>
> +      return new ForexRate(data.target, data.reference, data.value, data.date);
>
> +    } catch (e) {
>
> +      return null;
>
>
> Da gestire con un log o almeno un TODO
> ------------------------------
>
> In mf-frontend/src/model/ForexRate.ts
> <https://github.com/albertominetti/micro-finance/pull/2#discussion_r574086511>
> :
>
> > @@ -0,0 +1,45 @@
>
> +export default class ForexRate {
>
> +  private _target: string;
>
> +  private _reference: string;
>
> +  private _value: number;
>
> +  private _date: Date;
>
> +
>
> +  constructor(base: string, target: string, value: number, date: Date) {
>
> +    this._target = base;
>
> +    this._reference = target;
>
> +    this._value = value;
>
> +    this._date = date;
>
> +  }
>
> +
>
> +  get target(): string {
>
>
> Possiamo evitare tutta questa duplicazione?
> ------------------------------
>
> In pom.xml
> <https://github.com/albertominetti/micro-finance/pull/2#discussion_r574087111>
> :
>
> > @@ -25,6 +25,7 @@
>
>  	</properties>
>
>
>
>  	<modules>
>
> +        <module>mf-frontend</module>
>
>
> Possiamo chiamarlo semplicemente frontend
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/albertominetti/micro-finance/pull/2#pullrequestreview-588060757>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMCFGWLVWZYDNDIFC2KV5SLS6L2QBANCNFSM4XK5GSZQ>
> .
>

2021-02-11 22:22 UTC, albertominetti approved these changes

2021-02-11 22:23 UTC, merged